# Generated by Django 2.0.6 on 2018-06-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主机ID')),
                ('hostname', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机名称')),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')),
                ('private_ip', models.GenericIPAddressField(blank=True, default='127.0.0.1', null=True, verbose_name='内网IP')),
                ('cpu', models.CharField(blank=True, default='4核', max_length=50, null=True, verbose_name='CPU')),
                ('men', models.CharField(blank=True, default='8G', max_length=50, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, default='40G 100G', max_length=10, null=True, verbose_name='硬盘大小')),
                ('account', models.CharField(blank=True, default='csadministrator', max_length=100, null=True, verbose_name='账号')),
                ('port', models.CharField(blank=True, default='2048', max_length=100, null=True, verbose_name='端口')),
                ('password', models.CharField(blank=True, default='Cs@ecs#201801', max_length=100, null=True, verbose_name='密码')),
                ('webcode', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='WEB验证码')),
                ('webid', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='实例ID')),
                ('system', models.CharField(blank=True, default='Win2008 R2 x64', max_length=100, null=True, verbose_name='操作系统')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地区')),
                ('group', models.CharField(blank=True, max_length=300, null=True, verbose_name='所属组')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('cost', models.CharField(blank=True, default='-', max_length=500, null=True, verbose_name='费用')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
            },
        ),
        migrations.CreateModel(
            name='IDCInfo',
            fields=[
                ('idc_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=50, null=True, verbose_name='IDC Name')),
                ('login_url', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('account', models.CharField(blank=True, max_length=100, null=True, verbose_name='账号')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='密码')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='提供商')),
                ('linkman', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IDC 信息',
                'verbose_name_plural': 'IDC 信息',
            },
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='idc_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='assets.IDCInfo', verbose_name='机房类型'),
        ),
    ]
