# Generated by Django 2.0.6 on 2018-06-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180622_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='idc_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IDCInfo', verbose_name='机房类型'),
        ),
    ]
