# Generated by Django 2.0.6 on 2018-06-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180622_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=50, verbose_name='Group Name')),
                ('GroupNotes', models.CharField(max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '分组管理',
                'verbose_name_plural': '分组管理',
            },
        ),
    ]
