# Generated by Django 2.0.6 on 2018-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_groupinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfo',
            name='group',
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='group',
            field=models.ManyToManyField(to='assets.GroupInfo', verbose_name='所属组'),
        ),
    ]
