# Generated by Django 2.0.6 on 2018-06-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180622_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupInfo',
        ),
    ]
