# Generated by Django 2.0.6 on 2018-06-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180628_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinfo',
            options={'verbose_name': '项目信息', 'verbose_name_plural': '项目信息'},
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='ProjectService',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='服务名'),
        ),
    ]
