# Generated by Django 2.0.6 on 2018-06-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaLog',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False, verbose_name='LogID')),
                ('LoginUser', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('ActionUser', models.CharField(blank=True, max_length=50, null=True, verbose_name='Action User')),
                ('HostIP', models.GenericIPAddressField(blank=True, null=True, verbose_name='Host IP')),
                ('StartTime', models.CharField(blank=True, max_length=50, null=True, verbose_name='Start Time')),
                ('EndTime', models.CharField(blank=True, max_length=50, null=True, verbose_name='End Time')),
                ('Cmd', models.CharField(blank=True, max_length=500, null=True, verbose_name='action')),
                ('Result', models.GenericIPAddressField(blank=True, null=True, verbose_name='res')),
            ],
        ),
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False, verbose_name='LogID')),
                ('User', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Operation', models.CharField(max_length=500)),
                ('Result', models.GenericIPAddressField(blank=True, null=True, verbose_name='res')),
            ],
        ),
    ]
