# Generated by Django 2.0.6 on 2018-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salog',
            name='Result',
            field=models.TextField(blank=True, null=True, verbose_name='res'),
        ),
        migrations.AlterField(
            model_name='syslog',
            name='Result',
            field=models.TextField(blank=True, null=True, verbose_name='res'),
        ),
    ]
